/* =========================================
   1) TimescaleDB extension
   ========================================= */
CREATE EXTENSION IF NOT EXISTS timescaledb;


/* =========================================
   2) Enum (매수/매도 타입)
   ========================================= */
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'transaction_type') THEN
    CREATE TYPE transaction_type AS ENUM ('BUY', 'SELL');
  END IF;
END$$;


/* =========================================
   3) users
   ========================================= */
CREATE TABLE users (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      varchar NOT NULL,
  password   varchar NOT NULL,
  name       varchar NOT NULL,
  nickname   varchar NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_users_email    ON users (email);
CREATE UNIQUE INDEX uq_users_nickname ON users (nickname);

COMMENT ON TABLE users IS '회원';
COMMENT ON COLUMN users.email IS '이메일';
COMMENT ON COLUMN users.password IS '비밀번호';
COMMENT ON COLUMN users.name IS '이름';
COMMENT ON COLUMN users.nickname IS '닉네임';
COMMENT ON COLUMN users.created_at IS '생성시간';


/* =========================================
   4) stock_items
   ========================================= */
CREATE TABLE stock_items (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_symbol varchar NOT NULL,
  stock_name   varchar NOT NULL
);

CREATE UNIQUE INDEX uq_stock_items_symbol ON stock_items (stock_symbol);
CREATE UNIQUE INDEX uq_stock_items_name   ON stock_items (stock_name);

COMMENT ON TABLE stock_items IS '종목';
COMMENT ON COLUMN stock_items.stock_symbol IS '종목코드';
COMMENT ON COLUMN stock_items.stock_name IS '종목명';

/* =========================================
   5) account
   ========================================= */
CREATE TABLE account (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      bigint NOT NULL,
  start_asset  bigint NULL,
  total_asset  bigint NULL,
  account_name varchar NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_account_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_account_user_name ON account (user_id, account_name);

COMMENT ON TABLE account IS '가상 계좌';
COMMENT ON COLUMN account.start_asset IS '시작 자산(원)';
COMMENT ON COLUMN account.total_asset IS '총 자산(원)';
COMMENT ON COLUMN account.account_name IS '계좌이름';
COMMENT ON COLUMN account.created_at IS '생성시간';


/* =========================================
   6) like_stock_items (관심 종목)
   ========================================= */
CREATE TABLE like_stock_items (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       bigint NOT NULL,
  stock_item_id bigint NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_like_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_like_stock
    FOREIGN KEY (stock_item_id)
    REFERENCES stock_items(id)
    ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_like_user_stock ON like_stock_items (user_id, stock_item_id);
CREATE INDEX ix_like_user ON like_stock_items (user_id);

COMMENT ON TABLE like_stock_items IS '관심 종목';
COMMENT ON COLUMN like_stock_items.created_at IS '생성시간';


/* =========================================
   7) portfolio
   ========================================= */
CREATE TABLE portfolio (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id     bigint NOT NULL,
  stock_item_id  bigint NOT NULL,
  total_quantity int    NOT NULL CHECK (total_quantity >= 0),
  avg_price      bigint NOT NULL CHECK (avg_price >= 0),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NULL,

  CONSTRAINT fk_portfolio_account
    FOREIGN KEY (account_id)
    REFERENCES account(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_portfolio_stock
    FOREIGN KEY (stock_item_id)
    REFERENCES stock_items(id)
    ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_portfolio_account_stock ON portfolio (account_id, stock_item_id);
CREATE INDEX ix_portfolio_account ON portfolio (account_id);

COMMENT ON TABLE portfolio IS '포트폴리오';
COMMENT ON COLUMN portfolio.total_quantity IS '총보유수량';
COMMENT ON COLUMN portfolio.avg_price IS '평균단가(원)';
COMMENT ON COLUMN portfolio.created_at IS '생성시간';
COMMENT ON COLUMN portfolio.updated_at IS '마지막 수정시간';


/* =========================================
   8) transactions (hypertable)
   핵심: 처음부터 PK에 created_at 포함!
   ========================================= */
CREATE TABLE transactions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  account_id    bigint NOT NULL,
  stock_item_id bigint NOT NULL,
  type          transaction_type NOT NULL,
  price         bigint NOT NULL CHECK (price >= 0),
  quantity      int    NOT NULL CHECK (quantity > 0),
  created_at    timestamptz NOT NULL DEFAULT now(),

  -- ✅ Timescale 규칙 맞추기: partition key(created_at) 포함
  CONSTRAINT transactions_pkey PRIMARY KEY (id, created_at),

  CONSTRAINT fk_tx_account
    FOREIGN KEY (account_id)
    REFERENCES account(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_tx_stock
    FOREIGN KEY (stock_item_id)
    REFERENCES stock_items(id)
    ON DELETE RESTRICT
);

COMMENT ON TABLE transactions IS '거래내역';
COMMENT ON COLUMN transactions.type IS '매수/매도 타입';
COMMENT ON COLUMN transactions.price IS '매수/매도 가격(원)';
COMMENT ON COLUMN transactions.quantity IS '수량';
COMMENT ON COLUMN transactions.created_at IS '생성시간';

-- TimescaleDB: hypertable 변환
SELECT create_hypertable('transactions', 'created_at', if_not_exists => TRUE);

CREATE INDEX ix_tx_account_time ON transactions (account_id, created_at DESC);
CREATE INDEX ix_tx_stock_time   ON transactions (stock_item_id, created_at DESC);

/* =========================================
   수정
   ========================================= */

ALTER TABLE stock_items
  ADD COLUMN stock_type varchar NOT NULL,
  ADD COLUMN stock_country varchar NOT NULL,
  ADD COLUMN stock_alias varchar NULL;

COMMENT ON COLUMN stock_items.stock_type IS '종목유형(KOSPI/NASDAQ등)';
COMMENT ON COLUMN stock_items.stock_country IS '국가코드(KR, US 등)';
COMMENT ON COLUMN stock_items.stock_alias IS '종목별칭';

DROP INDEX IF EXISTS uq_stock_items_symbol;
DROP INDEX IF EXISTS uq_stock_items_name;

CREATE UNIQUE INDEX uq_stock_items_symbol ON stock_items (stock_symbol, stock_type);

/* =========================================
   주식종목정보 데이터 삽입
   ========================================= */

COPY stock_items (stock_name, stock_type, stock_symbol)
FROM 'C:\Users\whdid\project\ant-simulate\한국주식종목.xls'
WITH (
  FORMAT csv,
  HEADER true,
  ENCODING 'UTF8'
);